### ISSUE TITLE
不同時間開設的課程如何同時瀏覽

### ISSUE THREAD

**Issue by skyhong2002** [UniCourse-TW/API-Spec#12]
@ichiehg0v commented in [零時小學校專案孵化競賽](https://sch001.g0v.tw/dash/prj/PHfxJKR2hpg7f9rt58i9g6WZ_ZRo08): 
> 課程名稱可能會改變，要怎麼連結新舊名稱同屬一個課程，同樣的課程也可能有不同的授課老師，資料庫的建立除了符合 data base 之外，可以列出幾種主要的變動來作為設計參考

**Comment by JacobLinCool** [comment]
這個問題其實與我們之前討論過是否在 course instance 上層紀錄 course 類別相關，我們最終的決定是：**不額外紀錄 course-course instance 關係，只保留 course instance**。

我們希望**以課程內容為主體**，因此：
1. 如果發生名稱改動，多因課程內容 / 授課教師等課程核心因素產生變動，在此情況下我們應視為不同課程。
2. 如果發生內容類似但名稱更改的情形，系統應可以內容關鍵字自動建立課程間連結。

第一項我們以 schema 設計為約束條件，第二項則相關於我們的搜尋系統以及課程內容關鍵字分析系統。
