### ISSUE TITLE
Replace `time` with `created_at` and `last_updated_at`

### ISSUE THREAD

**Issue by uier** [UniCourse-TW/API-Spec#6]
Currently, most resourses have property `time` for storing timestamp, and it would be great to change the name from `time` to `created_at` or `created_time`.

For example:
https://github.com/UniCourse-TW/API-Spec/blob/b9c1571a5c525f3bad0d82341c3de7468d74694e/spec.yaml#L1059-L1062

Also, expect to have `updated_at` or `updated_time` for displaying the LAST UPDATED TIME to user in UI.

**Comment by skyhong2002** [comment]
目前 @JacobLinCool 是寫 CreateAt，應該就是解決了
